### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [guyandtheworld/reallyconfused#1]
Hey, your project is currently missing the Code of Conduct which adds value to any project even more. However, if you want me to add a PR with the Code of Conduct then provide me any contact address email which will be used in that Code of Conduct.

Thanks!

**Comment by guyandtheworld** [comment]
Hello @FahimFBA! Thanks a lot for recommending that. Feel free to do so and I shall merge it ASAP. My email is 4darshofficial (at) gmail.com.

**Comment by FahimFBA** [comment]
Submitted the PR. 😀
