### ISSUE TITLE
Add scroll to dropdown in home page. It's extending the entire page

### ISSUE THREAD

**Issue by Pranav4399** [guyandtheworld/reallyconfused#3]
![image](https://user-images.githubusercontent.com/28348429/144737131-402643d7-9772-4fcd-9c3f-81bdeb0744da.png)

**Comment by abcdeepakr** [comment]
Is this fixed? I can still see it overflowing on the desktop version

![image](https://user-images.githubusercontent.com/33338977/156876962-86957c81-100b-4591-8840-b178c4201717.png)

Maybe setting `max-height: 300px` will work

![image](https://user-images.githubusercontent.com/33338977/156877005-c6ff9dc2-0a50-4ea0-a6d4-192b0e6d96b1.png)

Creating a PR for the same.
